version: "3"
services:
  web-4000:
    build:
      context: .
    tty: true
    volumes:
      - "${PWD}:/app"
    ports:
      - "4000:4000"
  web-5000:
    build:
      context: .
      args:
        - "PORT=5000"
    tty: true
    volumes:
      - "${PWD}:/app"
    ports:
      - "5000:5000"
